name: Coverage Reporting

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - '**'

jobs:

  coverageReport:
    strategy:
      matrix:
        api-level: [21, 29]
      fail-fast: false
    runs-on: macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: create instrumentation coverage
        uses: reactivecircus/android-emulator-runner@v2.0.0
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          script: bash instrumentation.sh

      - name: create unit coverage
        run: ./gradlew jacocoTestDebugUnitTestReport jacocoTestCustomExampleDebugUnitTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
